
#-----------------------------------------------
#Config that does not have impact on performance
#-----------------------------------------------


random_seed: 0b011011

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:

#directory that have every dataset in it.
  data_dir: "./datasets"


  nb_train: "vctk/train.txt"
  nb_val: "vctk/test.txt"

  wb_train: "vctk/train.txt"
  wb_val: "vctk/test.txt"

#So for this case, wideband test dataset should be located at "/media/zeroone/target/test"

  batch_size: 16
  seg_len: 2
  
  num_workers: 16
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

#No information

#-----------------------------------------------
#3. Loss
#-----------------------------------------------

#No information

#-----------------------------------------------
#4. Optimizer (ADAM)
#-----------------------------------------------

optim:
  learning_rate: 0.0001

  B1: 0.5
  B2: 0.9


#-----------------------------------------------
#Training
#-----------------------------------------------

train:
  epoch_save_start: 0
  val_epoch: 10
  
#Path of output of validation. 
  output_dir_path: "./output"
  logger_path: "./logger"
  exp_path: "./RTBWE_logs"
  max_epochs: 350

  devices:
    - 0
    #- 1
    # -2 ... if you are using DDP

#-----------------------------------------------
#Predict
#-----------------------------------------------
predict:
  nb_pred_path: "/media/youngwon/Neo/NeoChoi/Projects/test/pred_nb" #The path to the directory containing the WAV files
  pred_output_path: "/media/youngwon/Neo/NeoChoi/Projects/test/pred_output" #The path to the directory where the output files will be saved.